In [36]:
import torch

In [44]:
x=torch.arange(4.)
x

tensor([0., 1., 2., 3.])

In [45]:
x.requires_grad_(True)
x.grad

In [47]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [48]:
# y=2*x*x
# y'=4*x 
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [56]:
# pytorch会累计梯度，因此做下一个时，需要清空累积值
x.grad.zero_()
print('x=',x)
y=x.sum()
print('y=',y)
# y=x_1+x_2+x_3+x_4
# y'_i==1
y.backward()
x.grad


x= tensor([0., 1., 2., 3.], requires_grad=True)
y= tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])

In [66]:
x.grad.zero_()
y=x*x
u=y.detach()# 将u看作常数，值为y，与x无关
z=u*x
print('x=',x)
print('u=',u)
# z=[u_i*x*i]
# z'=[u_i]
print('z=',z)
print('z.sum()=',z.sum())
z.sum().backward()
print('x.grad=',x.grad)

x= tensor([0., 1., 2., 3.], requires_grad=True)
u= tensor([0., 1., 4., 9.])
z= tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)
z.sum()= tensor(36., grad_fn=<SumBackward0>)
x.grad= tensor([0., 1., 4., 9.])


In [1]:
# 控制流中的求导计算
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

NameError: name 'torch' is not defined

In [4]:
list1=list(range(2))
list2=list(range(3))
print(list1)
print(list2)

[0, 1]
[0, 1, 2]


In [6]:
list3=[list1,list2]
print(list3)
list1[0]=2
print(list3)

[[0, 1], [0, 1, 2]]
[[2, 1], [0, 1, 2]]


In [9]:
a=1
def f(x):
    x-=1
print(a)
f(a)
print(a)

1
1
